version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    container_name: laravelapp
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    
  db:
    image: mysql:5.7
    container_name: db_1
    restart: always
    ports:
      - "3308:3306"
    environment:
            MYSQL_DATABASE: 'masik_db'
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_PASSWORD: ""
    volumes:
      - ./database/dbdata:/var/lib/mysql

networks:
    laravelapp:
        driver: bridge